"use strict";
// Generated by build.js on every build. Do not edit; do not serve.
module.exports = {
  "build": "ea64229b",
  "scopes": {
    "uv": "/parse/",
    "scramjet": "/parse/theta/"
  },
  "sw": "/queue.js",
  "routes": {
    "/apps": "/eb76b74",
    "/games": "/a4f138d",
    "/tabs": "/wb8704c",
    "/settings": "/f8c62c3"
  },
  "vendor": {
    "uv.bundle": "/deal/bridge.js",
    "uv.client": "/calc/index.js",
    "uv.handler": "/observer/manager.js",
    "uv.sw": "/deal/src/registry.js",
    "uv.config": "/of/matrix/resolver.js",
    "sj.all": "/tracer/registry/f.js",
    "sj.sync": "/3/client-stream.js",
    "sj.wasm": "/spending/decoder.wasm",
    "sj.config": "/we-v1/formatter.js",
    "baremux": "/delta/y.mjs",
    "baremux.worker": "/broker/scheduler.js",
    "epoxy": "/my/client.mjs",
    "libcurl": "/bind/index.mjs"
  },
  "analytics": {
    "id": "G-WKJQ5QHQTJ",
    "loader": "/3/decoder/profiler.js",
    "transport": "/that/3",
    "sink": "/units/1",
    "param": "wo",
    "key": [
      247,
      11,
      33,
      2,
      125,
      75,
      170,
      81
    ]
  }
};
